# Site settings
title: Marvin Wu
description: >
  My Study Notes On Git Docker and Other Cool stuff

baseurl: "" # the subpath of your site, e.g. /blog/
url: "marvinwu.github.io" # the base hostname & protocol for your site

author:
  fullname: marvinwu
  googleplus: https://www.google.com/marvinwu
  github: marvinwu
  twitter: marvinwu
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown